const userAge = 32;
const user = { name: 'John' };
user.age = userAge;
const admin = {};
Object.assign(admin, user);
admin.role = 'admin';
const { name, age, role } = admin;
console.log(user);
console.log(admin);
console.log(name, age, role);
